### ISSUE TITLE
Improper error message when sending embeds with files

### ISSUE THREAD

**Issue by ChaoticWeg** [ChaoticWeg/discord.sh#10]
Files can be sent with text, contrary to the error message

**Comment by krazykoder** [comment]
Hello @ChaoticWeg, 
I have been using this handy utility. 
When I use `--color` flag with text and files together I am getting 
`fatal: files must be sent on their own `

Did you finally patch a solution to this one - seems like you also had some similar error.

**Comment by fieu** [comment]
Hey @krazykoder,

Can you post the command you ran as well as the files in question? I will try and replicate it on my end.

**Comment by krazykoder** [comment]
This will throw the error. However try it without ` --color "0xFFFFFF" \ ` and it will work fine. 

`$HOME/.local/bin/discord.sh \                                                                
        --webhook-url=$WEBHOOK_URL \
        --color "0xFFFFFF" \                                              
        --text "Daily Monitor $HOSTNAME \n$(date)\n" \
        --file $HOME/Pictures/mouse.jpg \
        --username $HOSTNAME
`
`fatal: files must be sent on their own (i.e. without text or embeds)`

**Comment by fieu** [comment]
Ah right, well as it says in the error message, you cannot send files and embeds in one go.

The reason it works without `--color` is because that is a flag for the embed (which we can't use when using `--file` as well)

Going to fix the error to make it more clear. Can finally close this issue as well.
