### ISSUE TITLE
Any way for debugging?

### ISSUE THREAD

**Issue by ApertureDevelopment** [ChaoticWeg/discord.sh#13]
Hello, 

I am always recieving this error:
```parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 6, column 25```

and I would like to know how I can debug that or if there is a way to enable debug output

**Comment by ChaoticWeg** [comment]
As far as debugging goes, that's a really good question that I hadn't really considered.

As far as the control character issue, I encountered the same issue where `jq` errors out when trying to parse unescaped control characters. I wrote up some stuff about it in #8 regarding the workaround I had to use.
