### ISSUE TITLE
Add support for fields

### ISSUE THREAD

**Issue by fieu** [ChaoticWeg/discord.sh#14]
Add support for fields

**Comment by f0ff38** [comment]
Thx for scripts!
Add fields please )

**Comment by NurdTurd** [comment]
@f0ff38 If you know Bash and string manipulation, make a PR and we'd be glad to accept it!

**Comment by fieu** [comment]
I finally got around to it. Check out release v1.6: https://github.com/ChaoticWeg/discord.sh/releases/tag/v1.6

CC: @f0ff38
