### ISSUE TITLE
shopt: lastpipe: invalid shell option name

### ISSUE THREAD

**Issue by dozens** [ChaoticWeg/discord.sh#15]
Getting the following error on macos

discord.sh-1.3/discord.sh: line 6: shopt: lastpipe: invalid shell option name

with an invocation something like this:

discord.sh-1.3/discord.sh --webhook-url $webhook --title "title text" --text "$tags `cat $filename`"

**Comment by NurdTurd** [comment]
This is unrelated to the issue but just a tip. Make sure the file you are `cat`ing out is properly escaped.
https://stackoverflow.com/questions/3834839/how-to-escape-a-double-quote-inside-double-quotes

**Comment by NurdTurd** [comment]
`lastpipe` was introduced in Bash 4.2. Make sure you have the latest Bash version if possible or are at least on 4.2
