### ISSUE TITLE
Custom text + content of file?

### ISSUE THREAD

**Issue by marcelo321** [ChaoticWeg/discord.sh#19]
Hello, i am trying to send a custom text + the content of a file:

`./discord.sh --webhook-url "$WEBHOOK_URL" --text "$(cat filename | jq -Rs . | cut -c 2- | rev | cut -c 2- | rev)"` this sends the content of a file

and i want to send it like this:

./discord.sh --webhook-url "$WEBHOOK_URL" --text " customtxtHere ``` $(cat filename | jq -Rs . | cut -c 2- | rev | cut -c 2- | rev) (now this quote x3 `)"

i want to add the ` so it is in a nicer format when printing it in discord.

**Comment by marcelo321** [comment]
i ended up doing this 

`./discord.sh --webhook-url "https://discordapp.com/api/webhooks/" --text "output here:" --description "$(jq -Rs . <output.txt | cut -c 2- | rev | cut -c 2- | rev)"`

and works fine but if it is possible to include the 3 ` then it would be even better.

**Comment by ChaoticWeg** [comment]
If I understand correctly, then you should be able to just [escape the backticks](https://serverfault.com/a/286209) and throw some newlines in. Just bear in mind that you may also have to escape the backslash escape characters like this:

```bash
./discord.sh \
    --webhook_url "${WEBHOOK_URL}" \
    --text "Some text here\n\n\\\`\\\`\\\`$(<your subcmd here>)\\\`\\\`\\\`"
```

There's not a good way to handle this in discord.sh though, since the backticks will have been handled by bash before ever getting passed through to discord.sh.

**Comment by ChaoticWeg** [comment]
There's also [this in the docs](https://github.com/ChaoticWeg/discord.sh#proper-character-escaping) written by @NurdTurd. I don't know if it's helpful here, but it seems relevant.

**Comment by marcelo321** [comment]
Thanks! i will stick with the command i pasted above because it works fine now, i will test the one you gave me and it there is no errors i'll start implementing it. You can close this if you want to.

thank you.

**Comment by ChaoticWeg** [comment]
Sounds good! Point of note: I haven't tested that code at all, so it may or may not work. But it should point you in the right direction.

Good to hear you found a solution.
