### ISSUE TITLE
is there a way to include clickable url in description

### ISSUE THREAD

**Issue by thenamelessthing** [ChaoticWeg/discord.sh#21]
It is possible to include clickable url for text in description or have additional field under description?

Like on my highlited text in the screenshot?

Or event better, make image clickable with another url?

![image](https://user-images.githubusercontent.com/10235448/81459387-a8f03a00-916d-11ea-9a89-566c28702fbd.png)

**Comment by NurdTurd** [comment]
Hello @thenamelessthing, additional fields is something that has not implemented yet. Maybe someone can put in a PR however for now it's low on the priority list.

You can however add clickable links to your description by using the Markdown syntax.

```markdown
[Click Me](https://example.com)
```

Example:
```sh
./discord.sh \
  --webhook-url="$WEBHOOK" \
  --description "Check out this link: [Click Me](https://example.com)"
```
