### ISSUE TITLE
text under the --image  ?

### ISSUE THREAD

**Issue by thenamelessthing** [ChaoticWeg/discord.sh#22]
Hello, would there be a way to put text below the image when we use the --image argument? Or even place the text of the --description argument below the image?

**Comment by NurdTurd** [comment]
Hey @thenamelessthing, if you mean the footer, yes you can use the `--footer` argument to place text below the image.

**Comment by thenamelessthing** [comment]
Why didn't I think about it, the layout will be similar to the --description option?

**Comment by NurdTurd** [comment]
@thenamelessthing You cannot use Markdown in the footer unfortunately.

**Comment by thenamelessthing** [comment]
ok, it is possible to make  the --image url clickable?

**Comment by NurdTurd** [comment]
@thenamelessthing When clicking the image it will show the image in the Discord image preview interface. There is no way to make a clickable image that links to say another website.

**Comment by thenamelessthing** [comment]
Thank you for these explanations.
