### ISSUE TITLE
--text="xxx" doesn't work with newlines

### ISSUE THREAD

**Issue by 19wolf** [ChaoticWeg/discord.sh#23]

**Comment by fieu** [comment]
Hey @19wolf, everything seems fine on my end.

```sh
fieu@core:~$ ./discord.sh --text "Line1\nLine2"
```

![Screenshot](https://i.imgur.com/7wbfIjY.png)

Could you give me an example on how to reproduce the problem?

**Comment by 19wolf** [comment]
Yeah it turns out I need to escape the newlines. It took a minute to figure out but I ended up with `awk '{printf "%s\\n", $0}'`

**Comment by fieu** [comment]
Good to hear!
