### ISSUE TITLE
Data Input factor on shell script

### ISSUE THREAD

**Issue by rexdivakar** [ChaoticWeg/discord.sh#26]
/opt/vc/bin/vcgencmd measure_temp  >> /tmp/temp.log

tmp = /opt/vc/bin/vcgencmd measure_temp

./data/discord.sh-1.5/discord.sh --webhook-url="" --text tmp

## Not able to send the temperature of the device -- tried tmp, "tmp", "$tmp" still not working please help

**Comment by fieu** [comment]
Can you provide your scripts? I would need a little more information to help you. Feel free to redact anything sensitive.

**Comment by rexdivakar** [comment]
This is what i wrote,


tmp = /opt/vc/bin/vcgencmd measure_temp

./data/discord.sh-1.5/discord.sh --webhook-url="" --text $tmp

saved it as tmp.sh and ran it

but its not sending the temperature !! eventually I wrote a python script but I wish to rectify my mistake with the bash script so pls help me figure out the issue

**Comment by fieu** [comment]
@rexdivakar Bash is one of the very few languages where you must not put spaces for variable declaration.

Rather than
```bash
tmp = /opt/vc/bin/vcgencmd measure_temp
```

Do this
```bash
tmp=/opt/vc/bin/vcgencmd measure_temp
```

And it is best practice to put `$tmp` surrounded by quotes when using it. So:
```bash
./data/discord.sh-1.5/discord.sh --webhook-url="" --text "$tmp"
```

**Comment by fieu** [comment]
@rexdivakar Did this fix your problem?

**Comment by rexdivakar** [comment]
Yes that fixed the issue, thanks @fieu
