### ISSUE TITLE
in case embeds: timestamp not shown

### ISSUE THREAD

**Issue by dusselmann** [ChaoticWeg/discord.sh#35]
not sure why, but this command does not show the timestamp:

`./discord.sh \
  --webhook-url="$WEBHOOK" \
  --username "System Status" \
  --description "Here are your system stats!" \
  --field "Hostname;localhost;false" \
  --field "CPU;95%" \
  --field "Disk Usage;120/512GB"
  --timestamp`

**Comment by fieu** [comment]
I ran the command you provided:
```sh
./discord.sh --webhook-url="$WEBHOOK_URL" --username "System Status" --description "Here are your system stats!" --field "Hostname;localhost;false" --field "CPU;95%" --field "Disk Usage;120/512GB" --timestamp
```

Seems to work just fine for me. The problem you have isn't related to `discord.sh`, therefor I'm closing the issue.

![](https://limg.app/i/I6Mqv8.png)
