### ISSUE TITLE
Sending a bash string as description results in invalid JSON error

### ISSUE THREAD

**Issue by gjvdheuvel** [ChaoticWeg/discord.sh#36]
So when I have a message like:
`message="${user} is not following the rules as set in ${rules}"`

and then sending it like:
`discord.sh --webhook-url https://blabla.com/xyz --title "Hello world" --description "${message}"`

I then get:
```
error! {
  "code": 50109,
  "message": "The request body contains invalid JSON."
}
```

**Comment by fieu** [comment]
I believe you can just do `--description "$message"`

Make sure that `$user` and `$rules` are being passed?

Closing as it's not an issue with discord.sh
