### ISSUE TITLE
[Meta] Add CNAME record to redirect discord.sh domain name to this Github repo

### ISSUE THREAD

**Issue by kyle-dgcapital** [ChaoticWeg/discord.sh#40]
Whenever I try Google discord.sh, my browser omnibox takes me to the domain instead of searching. A CNAME would bring users to the Github page instead, which is probably what is intended anyway

**Comment by fieu** [comment]
The `.sh` TLD costs at minimum $30/year. There's also the fact that someone already owns the domain.

**Comment by kyle-dgcapital** [comment]
I assumed that one of the contributors owned the domain, as it directly mentions this repo: [https://discord.sh/](https://discord.sh/)

**Comment by fieu** [comment]
@kyle-dgcapital I guess I'll close this until they potentially come forward to offer up the domain.

WHOIS data is private.
