### ISSUE TITLE
Webhookurl | fatal: curl failed with code 7

### ISSUE THREAD

**Issue by msebastian100** [ChaoticWeg/discord.sh#51]
Hallo,
ich habe die web hook url mit angegeben einmal  so
./discord.sh --webhook-url=https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXX --text "Hello, world!"
und dann hab ich das einmal probiert mit der Datei ".webhook"  ich bekomme den gleichen fehler zurück.

fatal: curl failed with code 7

-------------------------------
ich finde dieses Projekt sehr interessant und bin gespannt was noch kommt :)

Grüße msebastian100

**Comment by fieu** [comment]
Try escaping your `webhook-url` flag value.

Example: `--webhook-url="https://discord.com/api/..."`

**Comment by msebastian100** [comment]
Thanks for the answer

Unfortunately I still get the same error:

 ./discord.sh --webhook-url="https://discord.com/api/webhooks/xxxxxxxxxxxxx" --text "Hello, world!"

**Comment by fieu** [comment]
> fatal: curl failed with code 7
Leaves me to believe you can't connect to `discord.com`

Source: https://stackoverflow.com/questions/32594838/curl-error-code-7#32594918

I'm closing this issue as I've just your command myself locally and it works without issue.

You have a `curl` issue, or something related to your network configuration. Nothing to do with `discord.sh`.
